# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
   # - name: Build with Maven
   #   run: mvn -B package --file pom.xml
    - name: Install Google Chrome # Using shell script to install Google Chrome
      run: |
       chmod +x ./InstallChromeBrowser.sh
       mv google-chrome-stable_current_amd64 /usr/bin/google-chrome
    - uses: nanasess/setup-chromedriver@master
     # with:
    # Optional: do not specify to match Chrome's version
      #  chromedriver-version: '88.0.4324.96'
    - run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
    - name: Run with Maven
      run: mvn test -Pselenium
