# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
   # - name: Build with Maven
   #   run: mvn -B package --file pom.xml
   # - uses: nanasess/setup-chromedriver@master
     # with:
    # Optional: do not specify to match Chrome's version
      #  chromedriver-version: '88.0.4324.96'
   # - run: |
       # export DISPLAY=:99
   #     chromedriver --url-base=/wd/hub &
   # - name: Selenium setup
   #   run: |
   #     wget https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar
   #     chromedriver --url-base=/wd/hub &
     #   xvfb-run java -Dwebdriver.chrome.driver=/usr/local/bin/chromedriver -jar selenium-server-standalone-3.141.59.jar
    - name: Install Chrome
      run: |
        set -ex
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install ./google-chrome-stable_current_amd64.deb
        sudo mv google-chrome-stable_current_amd64.deb /usr/bin/google-chrome
    - name: Run with Maven
      run: mvn test -Pselenium
